### ISSUE TITLE
Parameterized Testing

### ISSUE THREAD

**Issue by artburkart** [maxwellhealth/crush#1]
This crush unit testing library looks really cool! Any ideas on how I could add parameterized testing to it?

**Comment by jraede** [comment]
@artburkart It should probably go in /src/suite.php in the runTests method. Maybe a special naming convention for a parameterized test, and we can assume the name of the parameter factory based on the name of the method? Like testFooParameterized, and maybe the factory would be a property on the class called "fooParameters"
